version: "3.2"
services:
  rockmongo:
    image: jhaoheng/rockmongo
    container_name: rockmongo
    ports:
      - 27018:80
    volumes:
      - ./config.php:/app/config.php
    networks:
      - mongo
      
  mongo:
    image: mongo:3.7.3
    container_name: mongo
    ports:
      - 27017:27017/tcp
    networks:
      - mongo
    restart: always

networks:
  mongo:
    external: 
      name: mongo